config/routes.rb
Rails.application.routes.draw do
  scope 'admin' do
    resources :productos do
      member do
        put :limpiar_imagen
      end

      collection do
        put :generar_imagenes
      end
    end

    namespace :contabilidad do
      resources :cuentas
    end

    namespace :facturacion do
      resources :cuentas
    end
  end

  get 'acerca-de' => 'paginas#acerca_de'
  get 'contactanos' => 'paginas#contactenos'
  get 'frutas/:nombre' => 'frutas#buscar', as: :frutas_buscar
  get 'productos' => 'frutas#catalogo'

  root 'homepage#index'
end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/controllers/productos_controller.rb
# class comment
class ProductosController < ApplicationController
  layout 'admin'

  before_action :set_producto, only: [:show, :edit, :update, :destroy,
                                      :limpiar_imagen]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show; end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit; end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def limpiar_imagen
    @producto.imagen = nil
    @producto.save

    redirect_to productos_path, notice: 'Producto eliminado'
  end

  def generar_imagenes
    Producto.all.each do |producto|
      producto.imagen = producto.nombre.downcase + '.jpg'
      producto.save
    end
    redirect_to productos_path, notice: 'Exito'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_producto
    @producto = Producto.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def producto_params
    params.fetch(:producto, {})
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<%= link_to 'Generar imagenes', generar_imagenes_productos_path, method: :put %>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.imagen %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Limpiar imagen', limpiar_imagen_producto_path(producto), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>